on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Build project
        run: make build
      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: build/kafkai.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
